config/routes.rb
Rails.application.routes.draw do
  resources :projects
  patch 'drag/project'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "projects#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
    acts_as_list

    # broadcasts_to ->(project) { "projects" }

    after_create_commit -> { broadcast_append_to "projects" }
    # after_update_commit :broadcast_project_update
    after_destroy_commit -> { broadcast_remove_to "projects" }
    after_update_commit :broadcast_project_update

    private
  
    def broadcast_project_update
      # Only broadcast the whole list if the position has changed
      if saved_change_to_attribute?(:position)
        broadcast_replace_to "projects", target: "projects", partial: "projects/projects", locals: { projects: Project.order(:position) }
      else 
        broadcast_replace_to "projects"
      end
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/drag_controller.rb
class DragController < ApplicationController
    def project
        @project = Project.find(dragProjectParams[:id])
        @project.insert_at(dragProjectParams[:position].to_i + 1)
        # projects = Project.order(:position)
        # respond_to do |format|
        #     format.turbo_stream do 
        #         render turbo_stream: [
        #           turbo_stream.replace("projects", partial: "projects/projects", locals: { projects: projects })
        #         ]
        #     end
        # end
    end 

    private 
    def dragProjectParams
        params.require(:resource).permit(:id, :position)
    end 
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all.order(position: :asc)
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.turbo_stream
        # format.turbo_stream do 
        #   render turbo_stream: [turbo_stream.append("projects", partial: "projects/draggable", locals: { project: @project })]
        # end
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.turbo_stream
        # format.turbo_stream do 
        #   render turbo_stream: [
        #     turbo_stream.replace(@project, partial: "projects/project", locals: { project: @project })
        #   ]
        # end 
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy!

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.turbo_stream
      # format.turbo_stream do 
      #   render turbo_stream: [
      #     turbo_stream.remove(@project)
      #   ]
      # end 
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drag_helper.rb
module DragHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DragAndDrop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header id="header">
      <%= yield :header %>
    </header>
    <main class="p-4">
      <%= yield %>
    </main>
  </body>
</html>

app/views/projects/_draggable.html.erb
<% dragActions = "dragstart->drag#dragStart dragover->drag#dragOver dragenter->drag#dragEnter drop->drag#drop dragend->drag#dragEnd" %>
<%= content_tag(:div, class: "draggable border", draggable: true, data: { controller: "drag", action: dragActions, resource_id: project.id, url: "/drag/project", parent: "projects" }) do %>
    <%= render project %>
<% end %>

app/views/projects/_form.html.erb
<%= form_with(model: project, class: "contents") do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_field :description, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<%= turbo_frame_tag project, class: "" do %>
  <p class="my-5">
    <strong class="block font-medium mb-1">Title:</strong>
    <%= project.title %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= project.description %>
  </p>
  <p>
    <%= link_to "Show this project", project, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
     <%= link_to "Edit this project", edit_project_path(project), data: { turbo: false }, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
     <%= button_to "Destroy", project_path(project), method: :delete, class: "py-1 px-4 border border-red-600 bg-red-600 text-sm sm:text-md text-white rounded-md font-inter font-medium cursor-pointer" %>
  </p>
<% end %>

app/views/projects/_projects.html.erb
<%= turbo_frame_tag "projects", class: "min-w-full" do %>
    <% projects.each do |project| %>
        <%= render "projects/draggable", project: project %>
    <% end %>
<% end %>

app/views/projects/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing project</h1>

  <%= render "form", project: @project %>

  <%= link_to "Show this project", @project, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to projects", projects_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/projects/index.html.erb
<%= content_for :header do %>
      <h2>This is my header</h2>
      <%= button_to "Logout", destroy_user_session_path, method: :delete, data: { turbo: "false" }, class: "" %>
<% end %>
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Projects" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Projects</h1>
    <%= link_to "New project", new_project_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <%= turbo_stream_from "projects" %>

  <%= render "projects", projects: @projects %>

app/views/projects/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New project</h1>

  <%= render "form", project: @project %>

  <%= link_to "Back to projects", projects_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/projects/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @project %>

    <%= link_to "Edit this project", edit_project_path(@project), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to projects", projects_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this project", @project, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>